//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_image_server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple_image_server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new list.
        /// </summary>
        internal static string btnAddNewList {
            get {
                return ResourceManager.GetString("btnAddNewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnAddToList {
            get {
                return ResourceManager.GetString("btnAddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete list.
        /// </summary>
        internal static string btnDeleteSelectedList {
            get {
                return ResourceManager.GetString("btnDeleteSelectedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate list.
        /// </summary>
        internal static string btnDuplicateList {
            get {
                return ResourceManager.GetString("btnDuplicateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓.
        /// </summary>
        internal static string btnMoveListDown {
            get {
                return ResourceManager.GetString("btnMoveListDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑.
        /// </summary>
        internal static string btnMoveListUp {
            get {
                return ResourceManager.GetString("btnMoveListUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings folder.
        /// </summary>
        internal static string btnOpenSettingsfolder {
            get {
                return ResourceManager.GetString("btnOpenSettingsfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove image.
        /// </summary>
        internal static string btnRemoveImage {
            get {
                return ResourceManager.GetString("btnRemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings now.
        /// </summary>
        internal static string btnSaveSettingsNow {
            get {
                return ResourceManager.GetString("btnSaveSettingsNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Server.
        /// </summary>
        internal static string btnServertoggle {
            get {
                return ResourceManager.GetString("btnServertoggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable autostart on boot.
        /// </summary>
        internal static string btnStartOnBoot {
            get {
                return ResourceManager.GetString("btnStartOnBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow remoteaccess.
        /// </summary>
        internal static string chkAllowremoteAccess {
            get {
                return ResourceManager.GetString("chkAllowremoteAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart server (Will minimize to tray on start).
        /// </summary>
        internal static string chkAutostart {
            get {
                return ResourceManager.GetString("chkAutostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string chkListActive {
            get {
                return ResourceManager.GetString("chkListActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string chkListFriday {
            get {
                return ResourceManager.GetString("chkListFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string chkListMonday {
            get {
                return ResourceManager.GetString("chkListMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string chkListSaturday {
            get {
                return ResourceManager.GetString("chkListSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string chkListSunday {
            get {
                return ResourceManager.GetString("chkListSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string chkListThursday {
            get {
                return ResourceManager.GetString("chkListThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string chkListTuesday {
            get {
                return ResourceManager.GetString("chkListTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string chkListWednesday {
            get {
                return ResourceManager.GetString("chkListWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver random image from list.
        /// </summary>
        internal static string chkRandomImage {
            get {
                return ResourceManager.GetString("chkRandomImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool images from all matching active lists and deliver random.
        /// </summary>
        internal static string chkRandomImageFromAllActiveListsWithName {
            get {
                return ResourceManager.GetString("chkRandomImageFromAllActiveListsWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to update now.
        /// </summary>
        internal static string ClickToUpdateNow {
            get {
                return ResourceManager.GetString("ClickToUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client dropped connection {0}.
        /// </summary>
        internal static string ClientDroppedConnection {
            get {
                return ResourceManager.GetString("ClientDroppedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version {0}.
        /// </summary>
        internal static string CurrentVerionText {
            get {
                return ResourceManager.GetString("CurrentVerionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        internal static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable autostart on boot.
        /// </summary>
        internal static string DisableAutostartOnBoot {
            get {
                return ResourceManager.GetString("DisableAutostartOnBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty list.
        /// </summary>
        internal static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable autostart on boot.
        /// </summary>
        internal static string EnableAutostartOnBoot {
            get {
                return ResourceManager.GetString("EnableAutostartOnBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter list name.
        /// </summary>
        internal static string EnterListName {
            get {
                return ResourceManager.GetString("EnterListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error handling request {0}.
        /// </summary>
        internal static string ErrorHandlingRequest {
            get {
                return ResourceManager.GetString("ErrorHandlingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting server {0}.
        /// </summary>
        internal static string ErrorStartingServer {
            get {
                return ResourceManager.GetString("ErrorStartingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Image Server.
        /// </summary>
        internal static string Form1 {
            get {
                return ResourceManager.GetString("Form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server settings.
        /// </summary>
        internal static string groupBox1 {
            get {
                return ResourceManager.GetString("groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        internal static string groupBox2 {
            get {
                return ResourceManager.GetString("groupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements in list.
        /// </summary>
        internal static string groupBox3 {
            get {
                return ResourceManager.GetString("groupBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log output.
        /// </summary>
        internal static string groupBox4 {
            get {
                return ResourceManager.GetString("groupBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List settings.
        /// </summary>
        internal static string grpListsettings {
            get {
                return ResourceManager.GetString("grpListsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image already in list.
        /// </summary>
        internal static string ImageAlreadyInList {
            get {
                return ResourceManager.GetString("ImageAlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (inactive).
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (inactive because time of day).
        /// </summary>
        internal static string InactiveBecauseTimeOfDay {
            get {
                return ResourceManager.GetString("InactiveBecauseTimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (inactive because weekday).
        /// </summary>
        internal static string InactiveBecauseWeekday {
            get {
                return ResourceManager.GetString("InactiveBecauseWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loglevel.
        /// </summary>
        internal static string label10 {
            get {
                return ResourceManager.GetString("label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active timeperiod:.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active weekdays:.
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listname:.
        /// </summary>
        internal static string label5 {
            get {
                return ResourceManager.GetString("label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval (seconds each list shows same image):.
        /// </summary>
        internal static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing settings:.
        /// </summary>
        internal static string label7 {
            get {
                return ResourceManager.GetString("label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max width:.
        /// </summary>
        internal static string label8 {
            get {
                return ResourceManager.GetString("label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string label9 {
            get {
                return ResourceManager.GetString("label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list has images in it. Are you sure you want to delete it?.
        /// </summary>
        internal static string ListContainsImagesWarning {
            get {
                return ResourceManager.GetString("ListContainsImagesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List not found.
        /// </summary>
        internal static string ListNotFound {
            get {
                return ResourceManager.GetString("ListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error {0}.
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} available.
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new version available.
        /// </summary>
        internal static string NoNewVersionAvailable {
            get {
                return ResourceManager.GetString("NoNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select images to add to list.
        /// </summary>
        internal static string SelectImages {
            get {
                return ResourceManager.GetString("SelectImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select list first.
        /// </summary>
        internal static string SelectListFirst {
            get {
                return ResourceManager.GetString("SelectListFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not running.
        /// </summary>
        internal static string ServerNotRunning {
            get {
                return ResourceManager.GetString("ServerNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server running on port {0}.
        /// </summary>
        internal static string ServerRunningOnPort {
            get {
                return ResourceManager.GetString("ServerRunningOnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings folder could not be opened.
        /// </summary>
        internal static string SettingsfolderCouldNotBeOpened {
            get {
                return ResourceManager.GetString("SettingsfolderCouldNotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings folder not found.
        /// </summary>
        internal static string SettingsFolderNotFound {
            get {
                return ResourceManager.GetString("SettingsFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcelist not found.
        /// </summary>
        internal static string SourceListNotFound {
            get {
                return ResourceManager.GetString("SourceListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting server on port {0}.
        /// </summary>
        internal static string StartingServerOnPort {
            get {
                return ResourceManager.GetString("StartingServerOnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start server.
        /// </summary>
        internal static string StartServer {
            get {
                return ResourceManager.GetString("StartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statusStrip1.
        /// </summary>
        internal static string statusStrip1 {
            get {
                return ResourceManager.GetString("statusStrip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Server.
        /// </summary>
        internal static string StopServer {
            get {
                return ResourceManager.GetString("StopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
